
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] || 5 %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>

development:
  <<: *default
  database: db/development


test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'].sub(/^.+\//, '') %>

